### PR TITLE
Updated About Page

### PR DESCRIPTION
**Pull request by Hemashree21**
Resolved issue #66 

image

I have updated the Our story and mission text as well as added features with animations. The page is responsive across all devices.

@Harshil-Jani please check and let me know if any changes are required

### CODE REVIEW

**Comment by Harshil-Jani** [comment]
@Hemashree21 Thanks it's looking really good. Can you either remove the video section or replace it with some generated video ?

**Comment by Hemashree21** [comment]
Shall I remove the video and add a picture?

**Comment by Harshil-Jani** [comment]
@Hemashree21 Sure. That would also be a good idea.

**Comment by Harshil-Jani** [comment]
@Hemashree21 I see that two of your features have been merged into the same PR. I am okay with it and I can increase the level so you don't need to worry about de-merging branches. 

Another way round, If you are learning git and want to push them as separate PRs please feel free to do so. In case if you face any difficulties let me or @anudeeps0306 know about it and we can assist to help you with the git. 

The PR looks fine overall for dark mode and the about page too. Just a small suggestion if we can push the mode change button to some different place at the end of screen.

image

Also the text in career section looks off colour in dark mode
image

**Comment by Hemashree21** [comment]
> @Hemashree21 I see that two of your features have been merged into the same PR. I am okay with it and I can increase the level so you don't need to worry about de-merging branches.
> 
> Another way round, If you are learning git and want to push them as separate PRs please feel free to do so. In case if you face any difficulties let me or @anudeeps0306 know about it and we can assist to help you with the git.
> 
> The PR looks fine overall for dark mode and the about page too. Just a small suggestion if we can push the mode change button to some different place at the end of screen.
> 
> image
> 
> Also the text in career section looks off colour in dark mode image

Yeah, I was working on both the issues and didn't realise to push it into different branches. Thankyou for the suggestion and I will surely ask if I need any help. I'll do the changes and push it.

**Comment by Hemashree21** [comment]
@Harshil-Jani I have made the changes and the About Page change I have pushed in main branch and the Toggle button change I have made it in dev branch wrt #84. Are any more changes required?

Also when I try to view the deployed link it's showing like this.

image

Can you please grant me access?

**Review by Harshil-Jani — APPROVED** [review]

**Comment by Harshil-Jani** [comment]
Amazing work @Hemashree21

**Comment by Hemashree21** [comment]
> Amazing work @Hemashree21

Thankyou!

**Pull request merged**
