### PR TITLE
404 not found page added

### PR DESCRIPTION
**Pull request by RamakrushnaBiswal**
## Related Issue
issue #205 solved

## Description

404 not found page added with config## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image
## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by RamakrushnaBiswal** [comment]
@Harshil-Jani please review the PR

**Comment by anudeeps0306** [comment]
@RamakrushnaBiswal everything looks good , could you just convert image from png to webp

**Comment by RamakrushnaBiswal** [comment]
@anudeeps0306 ok I will

**Comment by RamakrushnaBiswal** [comment]
@anudeeps0306 converted png into webp

**Comment by Harshil-Jani** [comment]
> @anudeeps0306 converted png into webp

@RamakrushnaBiswal You probably updated the file name but forgot to update the link and thus, the image is not visible in the web. In code it still says 404.png instead of 404.webp

Over here

https://github.com/RamakrushnaBiswal/Nacto-Care/blob/7ff4bdeef523bb1dce549396463e4110499921eb/src/Pages/NotFound.jsx#L6

**Comment by RamakrushnaBiswal** [comment]
@Harshil-Jani @anudeeps0306 done

**Comment by Harshil-Jani** [comment]
Cute kitty. Looks good. Thanks @RamakrushnaBiswal

**Pull request merged**
