### PR TITLE
fix: greeting CI Activity

### LINKED ISSUE #159: BUG: Broken CI activity for greeting.yml
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

the current greeting action is throwing error.
image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by TenzDelek**
## Related Issue
Fixes #159 

## Description
rewrote the greeting 
## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Harshil-Jani** [comment]
@TenzDelek The whole purpose of the file is changed. It was meant to be as a thankyou note in the PR. Now the new change is completely opposite and is targeting the issues acknowledgement. 

#159 was asked to fix the CI and not rewrite the whole config.

**Comment by TenzDelek** [comment]
> @TenzDelek The whole purpose of the file is changed. It was meant to be as a thankyou note in the PR. Now the new change is completely opposite and is targeting the issues acknowledgement. 
> 
> 
> 
> #159 was asked to fix the CI and not rewrite the whole config.

Hmm interesting,@Harshil-Jani are you sure it is only meant for pr only? Cause from what I have understand it is meant for both pr and issue raised. The underlying issue #159 was happening after we raised an issue. 
I believe this pr covers both, will rectify once again and get back to you.

**Comment by TenzDelek** [comment]
Also why are we using checkout for a greeting CI?

**Comment by TenzDelek** [comment]
> @TenzDelek The whole purpose of the file is changed. It was meant to be as a thankyou note in the PR. Now the new change is completely opposite and is targeting the issues acknowledgement.
> 
> #159 was asked to fix the CI and not rewrite the whole config.

haha, indeed I overlook the issue. it was indeed the permission(which is not given for issue) as  you have mentioned in the issue. 
it must be fix now 
cc @Harshil-Jani

**Review by Harshil-Jani — APPROVED** [review]

**Pull request merged**
