### PR TITLE
[FIX] Fixed Confirm password masking not working 

### LINKED ISSUE #53: BUG: Password not masked in confirm Password section
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

**To Replicate:**
When signing up and entering the password in the confirm password section. The entered values are not being masked or hidden.

**Screenshots**
image

**Fix:**
- Changing the input type of the password from "confirm-password" to "password"

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Paper-Bag-dev**
# **Fixed bug where the confirm password section wasn't masking the password properly**

### CODE REVIEW

**Comment by Paper-Bag-dev** [comment]
@Harshil-Jani Can you help me a bit here?

**Comment by Harshil-Jani** [comment]
@Paper-Bag-dev Sure. What's the issue ?

**Comment by Paper-Bag-dev** [comment]
I have fixed the issue but some checks don't seem to be successful so can you look into them?

**Comment by Paper-Bag-dev** [comment]
Nevermind Thanks for your help! Please review and merge this request.

**Comment by Harshil-Jani** [comment]
@Paper-Bag-dev Can you add an option to toggle between masked pwd and unmasked pwd ? Like an eye shaped icon so that it avoids confusion while typing blindly. I am happy to upgrade this to level-2 for the second change in same PR.

**Comment by Paper-Bag-dev** [comment]
@Harshil-Jani yea sure I can do that!

**Comment by Paper-Bag-dev** [comment]
I have added the functionality to both the login and signup page's password inputs.
## Signup
image

## Login
image

**Review by Harshil-Jani — APPROVED** [review]
Thanks @Paper-Bag-dev

**Pull request merged**
