### PR TITLE
Updated Linkedin Handle and Contact us Handle #31

### PR DESCRIPTION
**Pull request by Ayush170803**
Successfully Updated the Social Media Handles as Provided.

### CODE REVIEW

**Comment by Ayush170803** [comment]
@Harshil-Jani Kindly merge the updated code

**Comment by Ayush170803** [comment]
@Harshil-Jani And please add the labels in PR also

**Comment by Harshil-Jani** [comment]
@Ayush170803 Contact us should not link to github. Instead it should link to the /contact route. For the github I was suggesting to remove the Twitter and Instagram fields and add a fresh field called "Github" and that should be linked to the repo.

**Review by Harshil-Jani — APPROVED** [review]

**Comment by Harshil-Jani** [comment]
Thankyou @Ayush170803

**Pull request merged**
