### PR TITLE
Stiffpixels feature scroll disable

### PR DESCRIPTION
**Pull request by Stiffpixels**
## Related Issue
#151 

## Description
took more time than I thought to disable scroll on nav menu open but I got it in the end. The scrolling is now disabled on mobile/tablet device when the navbar opens and the login and signup button match the ui of desktop.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

As you can see The scrollbars are disabled on mobile when navmenu opens.
https://github.com/Nactore-Org/Nacto-Care/assets/32983571/7c1048a8-38b3-4874-b216-208efa2bdcd5

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Harshil-Jani** [comment]
@Stiffpixels Have you checked out the desktop view of the site ?
On mobile view it looks amazing but for desktop it looks as shown below

image

**Comment by Stiffpixels** [comment]
> @Stiffpixels Have you checked out the desktop view of the site ?
> On mobile view it looks amazing but for desktop it looks as shown below
> 
> image
> 

Ok I will check it out.

**Comment by Stiffpixels** [comment]
for me its working well
https://github.com/Nactore-Org/Nacto-Care/assets/32983571/2f9bf912-7c6d-4652-a9d8-116a06cc44ca

**Comment by Stiffpixels** [comment]
is it still there @Harshil-Jani

**Comment by Harshil-Jani** [comment]
> for me its working well

Maybe check on chrome ? It's still a problem for desktop screens.

**Comment by Stiffpixels** [comment]
> > for me its working well
> 
> Maybe check on chrome ? It's still a problem for desktop screens.

what OS are you using Linux?

**Comment by Harshil-Jani** [comment]
> what OS are you using Linux?

Yes (BTW I use Arch)

**Comment by Stiffpixels** [comment]
> > what OS are you using Linux?
> 
> Yes (BTW I use Arch)

I donno what to say its working correctly on chrome and firefox. Can you give me team access to vercel to check out the deployment?
image

**Comment by Harshil-Jani** [comment]
@Stiffpixels  Yes sure. Just raise a request and I will approve from mail.
Also do check if your screen resolution is at 100% in chrome.

**Comment by Stiffpixels** [comment]
> Request accepted @Stiffpixels

Found the issue it was the useEffect being triggered initially. Changed the approach can you check now?

**Comment by Harshil-Jani** [comment]
@anudeeps0306 Just pining you in the PR because when I gave access of vercel to @Stiffpixels your access was revoked by default (Vercel has max 1 person access) Just request it back and I can approve it again.

**Review by Harshil-Jani — APPROVED** [review]

**Comment by Stiffpixels** [comment]
labels please

**Comment by anudeeps0306** [comment]
@Harshil-Jani 👍

**Pull request merged**
