### PR TITLE
created user login and signup

### PR DESCRIPTION
**Pull request by pm-2001**
Added user login and signup which includes password hashing, jwt token creation, alembic migration for models, better folder schema.
here is the folder schema:
image

### CODE REVIEW

**Comment by mdazfar2** [comment]
@pm-2001 
Could you share the screenshot of the particular code so that we can get a better idea about the campaign?

**Comment by Harshil-Jani** [comment]
@pm-2001 Sir 😢 . I lack technical skills to review 2818 files.

**Comment by pm-2001** [comment]
@Harshil-Jani  

> @pm-2001 Sir 😢 . I lack technical skills to review 2818 files.

@Harshil-Jani i have attached readme.txt file in backend, on how to run the backend code for login and signup

**Comment by pm-2001** [comment]
@Harshil-Jani by evening I will share the detailed code , currently I am not able to share.

**Comment by Harshil-Jani** [comment]
@pm-2001 This is whole backend what you have pushed. It doesn't justify the required change.

**Comment by pm-2001** [comment]
@Harshil-Jani I have added folders which were required for auth. I thought it would be better to understand and will hel in future.

**Comment by anudeeps0306** [comment]
@pm-2001 just add venv folder into gitignore , it will remove all unnecessary files and will make your pull request easy to read .

**Pull request closed without merging**
