### PR TITLE
FIXED #154 : Added a Feedback Form

### LINKED ISSUE #154: Feat: Missing Feedback Form on Website
### Describe the feature

**Problem:**

The website lacks a feedback form, which limits user interaction and prevents the collection of valuable user insights and suggestions.

**Solution:**

To address this issue, integrate a user-friendly feedback form. The form should include fields for:

- Name
- Email
- Rating (e.g., 1-5 stars)
- Comments/Suggestions

### Add ScreenShots

Below, you'll find images that provide an example of how the page will appear:

Feedback1
Feedback2

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by AkshitGarg24**
## Related Issue
Fixes #154 

## Description

The following changes have been made in the project:
- Added a "Help Us Improve!" sticky button on all pages of the website and included it in the footer.
- Implemented a dedicated feedback form on the website.

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/Nactore-Org/Nacto-Care/assets/153659573/db2022c8-ce36-474f-9f31-8015edb4c3ea

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.

### CODE REVIEW

**Comment by AkshitGarg24** [comment]
@Harshil-Jani Could you please merge my PR at your earliest convenience?

Additionally, kindly label the PR and add my name to the Assignees section before merging it.

Thank you!

**Comment by Harshil-Jani** [comment]
@AkshitGarg24 Thanks for this. But I see that the current submit button has no actions. Can you invoke the email to nactoreorganization@gmail.com with the response of the feedback ? In case you'd wonder how this works in code you can follow the current careers page and check submit form for nurse.

**Comment by AkshitGarg24** [comment]
@Harshil-Jani ,

I have implemented the requested changes. Please review them and let me know if any further adjustments are necessary.

Thank you!

**Review by Harshil-Jani — APPROVED** [review]

**Comment by AkshitGarg24** [comment]
@Harshil-Jani I request  you to please add my name in the assignees section of this PR.

**Pull request merged**
