### PR TITLE
Added Services Page

### PR DESCRIPTION
**Pull request by Hemashree21**
I have created a test database for patients and nurses with 6 fields and with information like name, location, qualification, hospital and profile for nurse and name, location, profile, age and services for patients. In the services page, based on the location input, the following details of the nurses and patients are displayed in their respective pages. I have made it responsive as well.

By default the location is selected as Delhi.

@Harshil-Jani can you please check and let me know if any changes are required?

image

image

image

image

### CODE REVIEW

**Review by anudeeps0306 — COMMENTED** [review]
It would be better if you are able to convert png to webp.

**Comment by Hemashree21** [comment]
> It would be better if you are able to convert png to webp.

Sure I will change that

**Comment by Hemashree21** [comment]
@Harshil-Jani @anudeeps0306 I updated all images to webp format

**Comment by Harshil-Jani** [comment]
Fair enough. Thanks @Hemashree21

**Pull request merged**
