### PR TITLE
Add New Nacto-Care Logo & Added digital signature to the logo SVG file

### PR DESCRIPTION
**Pull request by MehtabAsHellic**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

## Description
[Please include a brief description of the changes or features added]

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [x] Other (specify): Add New Nacto-Care Logo & Added digital signature to the logo SVG file

## Screenshots / videos (if applicable)
[
Nacto-CARE LOGO
](url)

## Checklist:
- [ ] I have performed a self-review of my code
- [ ] I have read and followed the Contribution Guidelines.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Review by Harshil-Jani — APPROVED** [review]

**Comment by Harshil-Jani** [comment]
@MehtabAsHellic Thanks a lot. Would you like to create a new issue to update the new logo everywhere on the website ? Also If you don't mind can you share your linkedin ? We can hit a mention for you on the Nactore Linkedin page for the new logo design.

**Comment by MehtabAsHellic** [comment]
> @MehtabAsHellic Thanks a lot. Would you like to create a new issue to update the new logo everywhere on the website ? Also If you don't mind can you share your linkedin ? We can hit a mention for you on the Nactore Linkedin page for the new logo design.

Sure.
[https://www.linkedin.com/in/mehtabarkhan/]

**Comment by Harshil-Jani** [comment]
@MehtabAsHellic Thanks. Please raise a new issue so we can keep a track of it.

**Comment by MehtabAsHellic** [comment]
As regard to #35 issues, Please provide me time beacuse as my exam is currenly going on.
Hope you understand
Thanks @Harshil-Jani

**Comment by MehtabAsHellic** [comment]
> @MehtabAsHellic Thanks. Please raise a new issue so we can keep a track of it.

Please assign it [#118](https://github.com/Nactore-Org/Nacto-Care/issues/118)

**Comment by Harshil-Jani** [comment]
> Please provide me time because as my exam is currently going on.

@MehtabAsHellic No hurry. Please take your time. All the best for your exams

**Comment by MehtabAsHellic** [comment]
> > Please provide me time because as my exam is currently going on.
> 
> @MehtabAsHellic No hurry. Please take your time. All the best for your exams

**Thank You**

**Pull request merged**
