### PR TITLE
Added Guidelines Page

### PR DESCRIPTION
**Pull request by Hemashree21**
Resolved issue #136

### CODE REVIEW

**Comment by Hemashree21** [comment]
@Harshil-Jani is this correct now? I already had a temp branch so I published it created a PR.

**Comment by Harshil-Jani** [comment]
No. This is incorrect since all the fixes that I made are currently in `Nactore-Org:temp` and not in `Hemshree21:temp`. So you need to change the source of this PR.

image

In order to do so (in case you are not aware of how to do)

image
image
image

That's it.

**Comment by Hemashree21** [comment]
image

Its showing this warning but I create PR button is still working. Can I create it?

**Comment by Harshil-Jani** [comment]
If the button works then yes please create it.

**Comment by Hemashree21** [comment]
No it's not working when I click on the button it's showing must be a collaborator

**Comment by Harshil-Jani** [comment]
Can you hard reset the temp with your fork ?

Do the following in your fork
```
git remote add upstream https://github.com/Nactore-Org/Nacto-Care.git
git checkout temp
git reset --hard 5131731f700daea5f42f41f402822a2ec8ae9b1b
git push -f
```

And it will automatically fix things in this PR itself and you would not need to do anything extra in new PR.

**Comment by Hemashree21** [comment]
@Harshil-Jani I pushed it

**Review by Harshil-Jani — APPROVED** [review]

**Comment by Harshil-Jani** [comment]
Thanks a lot @Hemashree21

**Comment by Harshil-Jani** [comment]
@Hemashree21 If you have some free time can you open up another issue to make sure that we are actually following the brand guidelines ourself?

By that I mean that in guidelines you have written font size , primary color, secondary color etc etc so can you pick up this task to audit and change things accordingly where we are not following the guidelines?

**Comment by Hemashree21** [comment]
> Thanks a lot @Hemashree21

I should be the one thanking you!

**Comment by Hemashree21** [comment]
> @Hemashree21 If you have some free time can you open up another issue to make sure that we are actually following the brand guidelines ourself?
> 
> By that I mean that in guidelines you have written font size , primary color, secondary color etc etc so can you pick up this task to audit and change things accordingly where we are not following the guidelines?

Sure I will open that right away.

**Comment by Hemashree21** [comment]
So the next time I am commiting I should pull all changes in my main branch and then directly raise a PR to the main branch right?

**Comment by Harshil-Jani** [comment]
> So the next time I am commiting I should pull all changes in my main branch and then directly raise a PR to the main branch right?

Ideal way is to fetch and pull your main with upstream and from that point in history checkout to a new branch and do all changes in new branch. Because it will give you flexibility to work on multiple issues simulatenously. Putting it all in main will be a huge mess if you work parallely on multiple things.

**Pull request merged**
