### PR TITLE
Patient Routes

### PR DESCRIPTION
**Pull request by Rhythm1710**
## Related Issue
Return all patients details #71

## Description
Patient Routes

## Type of PR

- [ ] Bug fix
- [X ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Checklist:
- [X ] I have performed a self-review of my code
- [ X] I have read and followed the Contribution Guidelines.
- [ X] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Rhythm1710** [comment]
Hi! @Harshil-Jani Its for patient details. Could you advice me which type of routes should I make more?

**Comment by Harshil-Jani** [comment]
Let's start with basic CRUD. 

We already have Create set up with auth. So for now

1. Get list of all the patients
2. Get a single patient
3. Edit any single patient (only after that patient has been authorized)
4. Delete the single patient data

And same for nurses. 

We can think of other endpoints as they come up in future. For time being, We would try to get this integrated into the F.E so that atleast site works as expected.

**Comment by Rhythm1710** [comment]
Hi! @Harshil-Jani I was working on these patient routes. In this the authentication is giving error of 422. Actually the change of custom form from username to email is giving error. I tried with username and it is working fine, but with custom email is giving error. I have been working on this from yesterday and I kinda feel stuck on it. I tried customising the passwordbearer as well but it is also not working.

**Comment by Harshil-Jani** [comment]
@Rhythm1710 Will checkout later tonight and let you know on this.

**Comment by Harshil-Jani** [comment]
Seems to work fine for me. Just a minor mistake in /patients  where ~id~ should be `patient_id`. Look at the video below

https://github.com/Nactore-Org/Nacto-Care/assets/79367883/cf2c8f97-e6c5-4ffc-baa3-0bb69df0c339

**Comment by Rhythm1710** [comment]
Ok! I will change that.

**Comment by Rhythm1710** [comment]
Hi! @Harshil-Jani Actually the issue I am facing is this. 

https://github.com/Nactore-Org/Nacto-Care/assets/65298117/df4c5088-7b68-4845-a0f2-c144738d0168


https://github.com/Nactore-Org/Nacto-Care/assets/65298117/19b310df-5e4b-4229-9072-add42be88242

**Comment by Rhythm1710** [comment]
I changed that and it is still coming as Unprocessable Entity.
Actually this issue is due to passswordbearer sending username instead of email.
Can we connect and solve this if you are free sometime?

**Pull request merged**
